name: Deploy GitHub Pages

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Semantic Version
        id: semver
        uses: paulhatch/semantic-version@v5.4.0
        with:
          tag_prefix: 'v'
          version_format: '${major}.${minor}.${patch}'
          bump_each_commit: false
          major_pattern: 'BREAKING CHANGE'
          minor_pattern: 'feat'

      - name: Update package.json version
        run: |
          npm version ${{ steps.semver.outputs.version }} --no-git-tag-version
          echo "NEW_VERSION=${{ steps.semver.outputs.version }}" >> $GITHUB_ENV

      - name: Build
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Commit & Push Version Changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add package.json package-lock.json
          git commit -m "chore: bump version to ${{ steps.semver.outputs.version }} [skip ci]" || echo "No changes to commit"
          git tag -a "v${{ steps.semver.outputs.version }}" -m "Release v${{ steps.semver.outputs.version }}"
          git push --follow-tags
